language: java

# list of supported JDKs
jdk:
  - oraclejdk8

# make gradlew executable
before_install:
 - chmod +x gradlew

# avoid uploading dependency caches that gradle generates
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/