language: java

# list of supported JDKs
jdk:
  - oraclejdk8

node_js: '7'

# make gradlew executable
before_install:
 - nvm install 7
 - chmod +x gradlew
 - npm --version

script:
  - gradle build

# avoid uploading dependency caches that gradle generates
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/