language: java

# sudo is required to install NodeJS
sudo: required

# we require JDK 1.8 or newer
jdk:
  - oraclejdk8

# install NodeJS with npm, and make gradlew executable
before_install:
  - nvm install 7
  - chmod +x gradlew

# invoke the Gradle build task to build the client and server code
script:
  - gradle build

# remove node_modules to keep archive size small
after_success:
  - rm -rf client/node_modules

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - client/node_modules
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

# deploy our combined application to Heroku
deploy:
  provider: heroku
  skip_cleanup: "true"
  api_key:
    secure: QOCCUCrqdryWs1L4U+oaPypgIszq97XJvkVOBY9znjZMtEAVrgoRfBZdI36zTArN4+DRMSKKOIifcAXacUSddZhEhrtxLUJtWbzV61GqFm/q5uRFHThrMpiAcJRufe4tVw96oqHgIwx/xw7UrsRG6ZDtAEoRkRtNlNMcUXLdw7AxyvVZc04PtA1Y8dIbJDyl3z3qMimbqOqLE9GLX65R7nmcMNKX08sGxpR+X6fHGbhv3sLqD5dkD2ELLaZBRk1zH+xcXSvCR6EQwlUmmnSSKE+ZoS35ew1Bks25PwP/dd0BxVeyMsxlbXllN20Qmd8ZBIAGLjX3u7wmPf/4G/vGe8elyZkaeGRPL3INXDHBMHXTS59mhHM5qIospCjlePapsx0TIbEAKgF6vXTuyPbR/WuqDiAVcdloH+rE2VolfiCTnNqdaJs8ys4oh9Xr0iYkW6++mzskUyYlsMT91DAB48jt9k9BS6VTq76XGZLj/SgEYU2dE+29A5hK2UoEq/Pq8FrKbD/uMDJj7gYOnZXYg9heOH8mi/Y12LWN4xB9WCjiEyJ06dSlLSf7ER4v3It52Dinjrbw4nWL5RzXZRg185sJlTat2d5+BEQzO5y8ZkaN4Bw5XlFPHmCRcn1FBBOE2N/JEQMXalY02FBk+Y6s7BAAZ5tICXV0afOgGsi138c=
  app: retro-realms
  on:
    repo: mbpolan/retro-realms
    branch: master