server:
  port: 9000

logging:
  level:
    com.mbpolan.retrorealms: DEBUG

spring:
  datasource:
    url: jdbc:h2:./db/server
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
  resources:
    staticLocations: file:./data/assets,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/